minuta/config/routes.rb
Rails.application.routes.draw do

  root 'clients#index'

  resources :clients
  resources :schedules do
    resources :client_schedules
  end
  resources :services

end

minuta/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

minuta/app/models/client.rb
class Client < User
  has_many :schedules, through: :client_schedules
  has_many :client_schedules

end

minuta/app/models/client_schedule.rb
class ClientSchedule < ApplicationRecord
  belongs_to :client
  belongs_to :schedule

  accepts_nested_attributes_for :schedule

end

minuta/app/models/employee.rb
class Employee < User
  belongs_to :owner
end

minuta/app/models/owner.rb
class Owner < User
  has_many :employees
  accepts_nested_attributes_for :employees

end

minuta/app/models/schedule.rb
class Schedule < ApplicationRecord

  has_one :client_schedule

  validates   :time,
              presence: true

  validates   :date,
              presence: true
end

minuta/app/models/service.rb
class Service < ApplicationRecord
  validates   :description,
              presence: true

  validates   :price,
              presence: true,
              :numericality =>{ :greater_than => 0 }
end

minuta/app/models/user.rb
class User < ApplicationRecord
end

minuta/app/controllers/ClientPersonImpl.rb
class ClientPersonImpl < PersonImpl {
    
    def do_task_it
        puts 'CLIENTE'
    end
}

minuta/app/controllers/Main.rb
class Main 
    Task task_owner = new Schedule
    Owner owner = new Owner(task_owner)
    @owner.do_it()

    task_owner = new Service
    @owner.receive_task(task_owner)
    @owner.do_it()
    task_owner.register()


end

minuta/app/controllers/OwnerPersonImpl.rb
class OwnerPersonImpl < PersonImpl 
    
        def do_task_it
            puts 'PROPRIETARIO'
        end
    
        # def receive_task
        #     @task=task
        # end
    
    #    def Owner (Task task)
    #        @task = task
    #    end
    
    #    def do_it
    #        puts("\n Proprietario")
    #        @task.do_task
    #    end
    
    #    def receive_task(Task task)
    #        @task=task
    #    end
    end

minuta/app/controllers/PersonImpl.rb
class PersonImpl
	def do_task_it
		raise "not imple3"
	end
	# def receive_task(task)
	# 	raise "not imple4"
	# end	
end

minuta/app/controllers/RatingTask.rb
#require 'service/Task.rb'

class RatingTask < TaskService 
    def do_task
        #puts(" realiza as devidas tarefas dos serviços")
        @implementor.do_task_it
    end
    
    # def do_task
    #     puts("  realiza as devidas tarefas de avaliacao")
    # end

    # def register
    # end

    # def tester
    #     puts("NOTA 10000000000")
    # end
end

minuta/app/controllers/ScheduleTask.rb
class ScheduleTask < Task 
    
    def do_task
        @implementor.do_task_it
    end

    # def register()
    #     # String service, time;
    #    # int day;

    #     puts("Qual serviço deseja agendar?")
    #     service = gets
    #     puts("Qual dia desse mes?")
    #     day = gets
    #     puts("Qual horario")
    #     time = gets

    #     if (Integer(day)>15)
    #         puts("servico agendado")
    #     else
    #         puts("tente novamente")
    #     end
    # end
	
end

minuta/app/controllers/ServiceTask.rb
class ServiceTask < TaskService
	def do_task
        #puts(" realiza as devidas tarefas dos serviços")
        @implementor.do_task_it
    end
    def register
      #  @task = Taks task   
        @implementor.receive_task     
        # puts("Qual serviço deseja cadastrar?")
        # service = gets
        # puts("quais dias da semana?")
        # days = gets
        # puts("SERVICO CADASTRADO , PARABENS")
    end
end

minuta/app/controllers/TaskService.rb
class TaskService 
    
    def initialize(implementor)
        @implementor = implementor
    end
    
        # def do_task
        # 	raise "not impl"
        # end
        
        # def register
        # 	raise "not imple 2"	
        # end
end

minuta/app/controllers/Teste.rb
class Task 
    
    def initialize(implementor)
        @implementor = implementor
    end
    
        # def do_task
        # 	raise "not impl"
        # end
        
    # def register
   #    	raise "not imple 2"	
    #end
end

class Service < Task 
	def do_task
        #puts(" realiza as devidas tarefas dos serviços")
        @implementor.do_task_it
    end
    def register
      #  @task = Taks task   
        @implementor.receive_task     
        # puts("Qual serviço deseja cadastrar?")
        # service = gets
        # puts("quais dias da semana?")
        # days = gets
        # puts("SERVICO CADASTRADO , PARABENS")
    end
end


# class Schedule < Task 
    
#     def do_task
#         puts(" realiza as devidas tarefas do agendamento")
#     end

#     def register()
#         # String service, time;
#        # int day;

#         puts("Qual serviço deseja agendar?")
#         service = gets
#         puts("Qual dia desse mes?")
#         day = gets
#         puts("Qual horario")
#         time = gets

#         if (Integer(day)>15)
#             puts("servico agendado")
#         else
#             puts("tente novamente")
#         end
#     end
	
# end

# class Rating < Task 
# 	def do_task
#         puts("  realiza as devidas tarefas de avaliacao")
#     end

#     def register
#     end

#     def tester
#         puts("NOTA 10000000000")
#     end
# end


class Person
	def do_task_it
		raise "not imple3"
	end
	def receive_task(task)
		raise "not imple4"
	end	
end

class Owner < Person 

    def do_task_it
        puts 'PROPRIETARIO'
    end

    def receive_task
       # @task_service=task
        puts("Qual serviço deseja cadastrar?")
        service = gets
        puts("quais dias da semana?")
        days = gets
        puts("SERVICO CADASTRADO , PARABENS")
    end

#    def Owner (Task task)
#        @task = task
#    end

#    def do_it
#        puts("\n Proprietario")
#        @task.do_task
#    end

#    def receive_task(Task task)
#        @task=task
#    end
end

# class Client < Person {
    
#     private Task task;

#     public Cliente(Task task){
#         this.task = task;
#     }

#     public Cliente(){}

#     public void doIt(){
#         puts("\n Cliente")
#         task.doTask();
#     }

#     public void receiveTask(Task task){
#         this.task = task;
#     }
# }

# class Employee 
#     include Person 

#     private Task task
    
#     def Employee (Task task)
#         @task = task
#     end

#     def do_it
#         puts("\n Funcionario")
#         @task.do_task
#     end

#     def receive_task(Task task)
#         @task=task
#     end
# end

service = Service.new(Owner.new)

# Drawing the rectangle with a drawing
# engine specific to a Mac computer.
service.register()

minuta/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = Client.all
  end

  def show
    id = params[:id]

    @client = Client.find(id)

  end

  def new
    @client = Client.new
  end

  def edit
    id = params[:id]

    @client = Client.find(id)

    Client.current_scope = @client
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      flash[:success] = "Cliente criado(a) com sucesso"
      redirect_to @client
    else
      render 'new'
    end
    
  end

  def update
    
    if @client.update(client_params)
      flash[:now] = "Cliente alterado(a) com sucesso"
      redirect_to @client
    else
      render 'edit'
    end    
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    flash[:alert] = "Cliente (a) excluído(a) com sucesso"
    redirect_to clients_path
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name_client, :birth_date, :cpf, :phone_client, :email_client, :password_client)
    end
end

minuta/app/helpers/application_helper.rb
module ApplicationHelper
end

minuta/app/helpers/clients_helper.rb
module ClientsHelper
end

minuta/app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

minuta/app/helpers/schedules_helper.rb
module SchedulesHelper
end

minuta/app/helpers/services_helper.rb
module ServicesHelper
end

minuta/app/views/clients/_form.html.erb
<%= form_for @client, :html => { :multipart => true }  do |f| %>
  <% if @client.errors.any? %>
    <div class="container">
      <div class="text-danger text-justify">
        <div id="error_explanation">
          <h2 class=""><%= pluralize(@client.errors.count, "erro") %> proibiram este formulario de ser salvo:</h2>
          <ul>
          <% @client.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <html lang="en">
      <head> 
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

      <!-- Website CSS style -->
      <link rel="stylesheet" type="text/css" href="assets/css/main.css">

      <!-- Website Font style -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
      
      <!-- Google Fonts -->
      <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

      <title>Admin</title>
    </head>
    <body>
      <div class="container">
        <div class="row main">
          <div class="panel-heading">
          <div class="main-login main-center">
            <form class="form-horizontal" method="post" action="#">
              
              <div class="form-group">
                <%= f.label :name_client, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-user"></span>
                     Nome
                  </span>
                  <%= f.text_field :name_client, class:"form-control", placeholder:"Nome do usuário" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :phone_client, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-phone"></span>
                     Telefone
                  </span>
                  <%= f.text_field :phone_client, class:"form-control", placeholder:'Somente números com DDD.' %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :cpf, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">CPF</span>
                  <%= f.text_field :cpf, class:"form-control cpf active", placeholder:"Somente números."%>
                </div>
                <p>
                  <small class="text-muted text-lowercase sr-only">(somente numeros)</small>
                </p>
              </div>

              <div class="form-group">
                <%= f.label :birth_date, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-gift"></span>
                     Data de nascimento
                  </span>
                  <%= f.date_field :birth_date, class:"form-control", placeholder:"Ex.: dd/mm/aaaa" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :email_client, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-user"></span>
                     Email
                  </span>
                  <%= f.text_field :email_client, class:"form-control", placeholder:"Email" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :password_client, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-password"></span>
                     Senha
                  </span>
                  <%= f.text_field :password_client, class:"form-control", placeholder:"Senha" %>
                </div>
              </div>

              <%= f.button '<span class="fa fa-check"></span> Salvar'.html_safe, type:"submit", class:'btn btn-lg btn-success' %>
              </div>
            </form>
          </div>
        </div>
      </div>

      <script type="text/javascript" src="assets/js/bootstrap.js"></script>
    </body>
  </html>
<% end %>

minuta/app/views/clients/_form_edit.html.erb
<%= form_for @client, :html => { :multipart => true }  do |f| %>
  <% if @client.errors.any? %>
    <div class="container">
      <div class="text-danger text-justify">
        <div id="error_explanation">
          <h2 class=""><%= pluralize(@client.errors.count, "erro") %> proibiram este formulario de ser salvo:</h2>
          <ul>
          <% @client.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

      <!-- Website CSS style -->
      <link rel="stylesheet" type="text/css" href="assets/css/main.css">

      <!-- Website Font style -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

      <!-- Google Fonts -->
      <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

      <title>Admin</title>
    </head>
    <body>
      <div class="container">
        <div class="row main">
          <div class="panel-heading">
                   <div class="panel-title text-center">
                      <h1 class="title">Editar o cliente : <%=@client.name_client %></h1>
                      <hr />
                    </div>
                </div>
          <div class="main-login main-center">
            <form class="form-horizontal" method="post" action="#">

              <div class="form-group">
                <%= f.label :name_client, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-user"></span>
                     Nome
                  </span>
                  <%= f.text_field :name_client, class:"form-control", placeholder:"Nome do usuário" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :phone_client, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-phone"></span>
                     Telefone
                  </span>
                  <%= f.text_field :phone_client, class:"form-control", placeholder:'Somente números com DDD.' %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :cpf, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">CPF</span>
                  <%= f.text_field :cpf, class:"form-control cpf active", placeholder:"Somente números."%>
                </div>
                <p>
                  <small class="text-muted text-lowercase sr-only">(somente numeros)</small>
                </p>
              </div>

              <div class="form-group">
                <%= f.label :birth_date, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-gift"></span>
                     Data de nascimento
                  </span>
                  <%= f.date_field :birth_date, class:"form-control", placeholder:"Ex.: dd/mm/aaaa" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :email_client, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-user"></span>
                     Email
                  </span>
                  <%= f.text_field :email_client, class:"form-control", placeholder:"Email" %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :password_client, class:"sr-only" %>
                <div class="input-group">
                  <span class="input-group-addon">
                    <span class="fa fa-password"></span>
                     Senha
                  </span>
                  <%= f.text_field :password_client, class:"form-control", placeholder:"Senha" %>
                </div>
              </div>
              <%= link_to '<span class="fa fa-address-card"> Voltar</span>'.html_safe, client_path(@client), class:'btn btn-lg btn-warning' %>
              <%= f.button '<span class="fa fa-check"> Salvar</span>'.html_safe, type:"submit", class:'btn btn-lg btn-success' %>
              </div>
            </form>
          </div>
        </div>
      </div>

      <script type="text/javascript" src="assets/js/bootstrap.js"></script>
    </body>
  </html>
<% end %>

minuta/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name client</th>
      <th>Birth date</th>
      <th>Cpf</th>
      <th>Phone client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name_client %></td>
        <td><%= client.birth_date %></td>
        <td><%= client.cpf %></td>
        <td><%= client.phone_client %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

minuta/app/views/clients/new.html.erb
<section class="content-section" id="create">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <h1 class="text-center text-uppercase">
          <span class="fa fa-user-plus"></span> Criar Cliente
        </h1>
        <%= render 'clients/form' %>
      </div>
    </div>
  </div>
</section>

minuta/app/views/clients/show.html.erb
<section class="content-section" id="alumns-desc">
  <div class="container">
    <div class="pull-right">
        <%= link_to '<span class="fa fa-edit"></span>Editar'.html_safe, edit_client_path(@client), class:"btn btn-sm btn-default" %>
        
        <%= link_to '<span class="fa fa-times"></span>Excluir'.html_safe, "", method: :delete, class:'btn btn-sm btn-danger', data: { confirm: 'Tem certeza? Essa alteração não pode ser desfeita.'}, name:"delete"  %>
      	<%= link_to '<span class="fa fa-address-card"></span> Voltar'.html_safe, clients_path, class:'btn btn-sm btn-warning' %>
    </div>
    <div class="row item">
      <div class="col-sm-12 col-md-4">
        <%= image_tag("avatar_250x300.png", alt: "", class: "img-responsive" ) %>
      </div>
      <div class="col-sm-12 col-md-8 text-capitalize descript">
        <h3 class="">Nome: <%= @client.name_client %></h3>
        <h4 class="">Telefone: <%= @client.phone_client %></h4>
        <h4 class="">CPF: <%= @client.cpf %></h4>
        <h4 class="">Data de Nascimento: <%= @client.birth_date %></h4>
      </div>
    </div>
  </div>
</section>